version: "2"
services: 
  app: 
    container_name: app
    restart: always
    build: .
    ports: 
      - "8082:8082"
    links: 
      - mongo
    networks:
      - webappnetwork
  # api:
  #   container_name: api
  #   restart: always
  #   build: routes
  #   ports: 
  #     - 8083:8083
  #   links:
  #     - app
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/bandDB
    ports:
      - "27017:27017"
    command: mongod --noauth --smallfiles
    networks:
      - webappnetwork
networks: 
  webappnetwork:
    driver: bridge