version: "2"
services: 
  app: 
    container_name: app
    restart: always
    build: .
    ports: 
      - '8082:8082'
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:  
      - ./data:/data/db
    ports:
      - '27017:27017'
    # command: mongod --bind_ip 127.0.0.1
    command: mongod --noauth --smallfiles
  # api:
  #   container_name: api
  #   restart: always
  #   build: routes
  #   ports: 
  #     - 8083:8083
  #   links:
  #     - app